//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAcademiaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoFisica
    {
        public int id { get; set; }
        public System.DateTime dataRealizacao { get; set; }
        public string anamnese { get; set; }
        public string dobrasCutaneas { get; set; }
        public string exameErgonometrico { get; set; }
        public int idFisioterapeuta { get; set; }
        public int idAluno { get; set; }
    }
}
