//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAcademiaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empregado
    {
        public int id { get; set; }
        public string identidade { get; set; }
        public string cpf { get; set; }
        public string nome { get; set; }
        public bool aulaGrupo { get; set; }
        public bool aulaMusculacao { get; set; }
        public string senha { get; set; }
        public int idPerfil { get; set; }
    }
}
