//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAcademiaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int id { get; set; }
        public int idAluno { get; set; }
        public decimal valor { get; set; }
        public System.DateTime dataProxima { get; set; }
        public System.DateTime dataBaseInicio { get; set; }
        public System.DateTime dataBaseFim { get; set; }
    }
}
