//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAcademiaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROJETOACADEMIAEntities : DbContext
    {
        public PROJETOACADEMIAEntities()
            : base("name=PROJETOACADEMIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<AvaliacaoFisica> AvaliacaoFisica { get; set; }
        public virtual DbSet<Empregado> Empregado { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<RegistraPresenca> RegistraPresenca { get; set; }
        public virtual DbSet<TipoPerfil> TipoPerfil { get; set; }
        public virtual DbSet<TipoPlano> TipoPlano { get; set; }
        public virtual DbSet<Ferias> Ferias { get; set; }
    }
}
